version: "3.9"

services:
  app:
    build: .
    container_name: catalos-core
    ports:
      - "8071:8071"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
