server:
  port: 8071
  error:
    include-stacktrace: never

spring:
  application:
    name: catalos
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://catalos_read_write_user:Yht4gVfjC9Jdr5er@flourimus-b2c-core.rwrgd.mongodb.net/catalos_backend_dev2}

jwt:
  secret: ${JWT_SECRET:my-very-secure-secret-must-be-at-least-32-chars}
  expirationMs: 86400000
