server:
  port: 8071
  error:
    include-stacktrace: never

spring:
  application:
    name: catalos
  data:
    mongodb:
      uri: mongodb+srv://<credentials>/database

jwt:
  secret: my-very-secure-secret-must-be-at-least-32-chars
  expirationMs: 86400000
