name: Build, Push and Deploy to Oracle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/catalos-core:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/catalos-core:latest

      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ubuntu
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            echo "==> Logging into Docker Hub"
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            echo "==> Stopping old container (if running)"
            docker stop catalos-core || true
            docker rm catalos-core || true

            echo "==> Pulling latest image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/catalos-core:latest

            echo "==> Running new container"
            docker run -d --restart always --name catalos-core -p 8071:8071 \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e JWT_EXPIRATION_MS=86400000 \
              ${{ secrets.DOCKER_USERNAME }}/catalos-core:latest

