name: Deploy to Oracle Cloud

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: SSH into Oracle Cloud and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ubuntu
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            echo "==> Logging into Docker Hub"
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            echo "==> Stopping old container (if running)"
            docker stop catalos-core || true
            docker rm catalos-core || true

            echo "==> Pulling latest image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/catalos-core:latest

            echo "==> Running new container"
            docker run -d --restart always --name catalos-core -p 8071:8071 \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e JWT_EXPIRATION_MS="${{ secrets.JWT_EXPIRATION_MS }}" \
              -e AUTH_APP_SERVER="${{ secrets.AUTH_APP_SERVER }}" \
              ${{ secrets.DOCKER_USERNAME }}/catalos-core:latest
